name: Primeiro Workflow Linuxtips

on:
  push: 
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-lastest
    steps:
      - name: Confere versão do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: "echo fazendo o curso de Github Actions da Linuxtips"